### ISSUE TITLE
Errors in playing a spotify playlist

### ISSUE THREAD

**Issue by git-kush** [melody-bot/Melody#55]
#### Using the play command with a Spotify playlist URL gives the following error -
```
(node:4239) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'track' of undefined
    at Player.<anonymous> (/workspaces/Melody/node_modules/erela.js/dist/structures/Player.js:239:47)
    at Generator.next (<anonymous>)
    at /workspaces/Melody/node_modules/erela.js/dist/structures/Player.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspaces/Melody/node_modules/erela.js/dist/structures/Player.js:4:12)
    at Player.play (/workspaces/Melody/node_modules/erela.js/dist/structures/Player.js:212:16)
    at Object.run (/workspaces/Melody/src/music-cmds/play.js:80:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4239) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Details: 
After using the command, tracks do get enqueued, but nothing gets played in the voice channel. However, the `nowplaying` command does show the current track being played (while it is absolutely silent) and the duration and thumbnail are `undefined`.

### Note: 
I tried to downgrade the erela.js package as well as use old code from private archived repository (which used to show no errors) but it still shows the same error. The problem is probably not isolated to the play.js file.

**Comment by noneedofit** [comment]
Fixed after package update.
